/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2023-02-25 07:38:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import mvc.model.boardDTO;

public final class board_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/영석/Documents/GitHub/ITedunet_TP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CDC/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1676985566219L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("mvc.model.boardDTO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	String username = (String) session.getAttribute("username");
	System.out.println("게시판의닉넴: "+username);
	List boardlist = (List)request.getAttribute("boardlist");
	System.out.println("List: "+boardlist);
	int total_record = ((Integer) request.getAttribute("total_record")).intValue();
	System.out.println("전체글: "+total_record);
	int total_page = ((Integer) request.getAttribute("total_page")).intValue();
	System.out.println("전체페이지: "+total_page);
	int pageNum = ((Integer) request.getAttribute("pageNum")).intValue();
	System.out.println("현재페이지넘버: "+pageNum);
	String tag_src = (String)request.getAttribute("tag_src");
	System.out.println("동물이미지소스: "+tag_src);
	String tag_value = (String)request.getAttribute("tag_value");
	System.out.println("동물태그: "+tag_value);

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./resources/css/board.css\">\r\n");
      out.write("	<title>커뮤니티 게시판</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./header.jsp", out, false);
      out.write("\r\n");
      out.write("    <div class =\"com_name\">\r\n");
      out.write("        <h1>우리아이자랑</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"midbox\">\r\n");
      out.write("            <div class=\"seabox\">\r\n");
      out.write("                <div class=\"search\">\r\n");
      out.write("                    <input type=\"text\" placeholder=\"찾으시는 글이 있으신가요?\" maxlength=\"130\" class=\"com_search\" enterkeyhint=\"search\" value=\"\">\r\n");
      out.write("                    <button class=\"button\" type=\"submit\" >\r\n");
      out.write("                        <img src=\"./resources/img/seabut.png\" alt=\"search\">\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"textbox\" id=\"hotline\">인기글</div>\r\n");
      out.write("                <div class=\"bestlist\">\r\n");
      out.write("                    <div class=\"bestbox\">\r\n");
      out.write("                        <div class=\"list1\">\r\n");
      out.write("                            <div class=\"listlabel\">\r\n");
      out.write("                                <div class=\"labelname\">\r\n");
      out.write("                                    <img class=\"catface\" src=\"./resources/img/catface.png\" alt=\"\">\r\n");
      out.write("                                    <div class=\"cattext\">고양이\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"listhead\">\r\n");
      out.write("                                    울집고양이귀엽\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"listtext\">\r\n");
      out.write("                                    대충 우리집 고양이가 귀엽다는 말\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"reply\">\r\n");
      out.write("                                    <span class=\"re1\">\r\n");
      out.write("                                        답변 \r\n");
      out.write("                                        3\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <span class=\"day\">2023.02.07</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"listgo\">\r\n");
      out.write("                                    <a href=\"#\" class=\"gobutton\">바로가기</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"list1\">\r\n");
      out.write("                            <div class=\"listlabel\">\r\n");
      out.write("                                <div class=\"labelname\">\r\n");
      out.write("                                    <img class=\"dogface\" src=\"./resources/img/dogface.png\" alt=\"\">\r\n");
      out.write("                                    <div class=\"dog\">강아지</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"listhead\">\r\n");
      out.write("                                    울집 강아지 왜이럼?\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"listtext\">\r\n");
      out.write("                                    대충 우리집 강아지가 귀엽다는 말\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"reply\">\r\n");
      out.write("                                    <span class=\"re1\">\r\n");
      out.write("                                        답변 \r\n");
      out.write("                                        3\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <span class=\"day\">2023.02.07</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"listgo\">\r\n");
      out.write("                                    <a href=\"#\" class=\"gobutton\">바로가기</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"list1\">\r\n");
      out.write("                            <div class=\"listlabel\">\r\n");
      out.write("                                <div class=\"labelname\">\r\n");
      out.write("                                    <img src=\"./resources/img/catface.png\" alt=\"\">\r\n");
      out.write("                                    <div class=\"cattext\">고양이</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"listhead\">\r\n");
      out.write("                                    울집 고양이가 낙법을 써요ㅇㅇㅇㅇ\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"listtext\">\r\n");
      out.write("                                    대충 우리집 고양이가 귀엽다는 말\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"reply\">\r\n");
      out.write("                                    <span class=\"re1\">\r\n");
      out.write("                                        답변 \r\n");
      out.write("                                        3\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <span class=\"day\">2023.02.07</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"listgo\">\r\n");
      out.write("                                    <a href=\"#\" class=\"gobutton\">바로가기</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"list1\">\r\n");
      out.write("                            <div class=\"listlabel\">\r\n");
      out.write("                                <div class=\"labelname\">\r\n");
      out.write("                                    <img class=\"dogface\" src=\"./resources/img/dogface.png\" alt=\"\">\r\n");
      out.write("                                    <div class=\"dog\">강아지</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"listhead\">\r\n");
      out.write("                                    울집 강아지 왜이럼?\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"listtext\">\r\n");
      out.write("                                    대충 우리집 강아지가 귀엽다는 말\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"reply\">\r\n");
      out.write("                                    <span class=\"re1\">\r\n");
      out.write("                                        답변 \r\n");
      out.write("                                        3\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <span class=\"day\">2023.02.07</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"listgo\">\r\n");
      out.write("                                    <a href=\"#\" class=\"gobutton\">바로가기</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr class=\"borderline\">\r\n");
      out.write("        <div class=\"loungebox\">\r\n");
      out.write("            <div class=\"filterbox\">\r\n");
      out.write("                <div class=\"filterbt\">\r\n");
      out.write("                    <div class=\"radiobox\">\r\n");
      out.write("                        <input class=\"radiobt\" type=\"radio\" id=\"newest\" name=\"question\" value=\"최신순\" checked>\r\n");
      out.write("                        <label for=\"newest\">최신순</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"filterbt\">\r\n");
      out.write("                    <div class=\"radiobox\">\r\n");
      out.write("                        <input class=\"radiobt\" type=\"radio\" id=\"popular\" name=\"question\" value=\"인기순\">\r\n");
      out.write("                        <label for=\"popular\">인기순</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"filterbt\">\r\n");
      out.write("                    <div class=\"radiobox\">\r\n");
      out.write("                        <input class=\"radiobt\" type=\"radio\" id=\"views\" name=\"question\" value=\"조회순\">\r\n");
      out.write("                        <label for=\"views\">조회순</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"writebox\">\r\n");
      out.write("                    <a href=\"./commuwrite.action\" class=\"write\">글쓰기</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"loungelist\">\r\n");
      out.write("                <div class=\"conlist\">\r\n");
      out.write("                	");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /board.jsp(176,17) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/board.jsp(176,17) '${boardlist }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${boardlist }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
        // /board.jsp(176,17) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("board");
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("                    <div class=\"content\">\r\n");
              out.write("                        <div class=\"colist\">\r\n");
              out.write("                            <div>\r\n");
              out.write("                                <div class=\"colbt\">\r\n");
              out.write("                                	<img  src=\"./resources/img/catface.png\" alt=\"\">\r\n");
              out.write("                                    <img src=\"");
              out.print(tag_src );
              out.write("\" alt=\"\">\r\n");
              out.write("                                    <img src=\"./resources/img/borad/catface.png\" alt=\"\">\r\n");
              out.write("                                    <div class=\"cattext1\">");
              out.print(tag_value );
              out.write("</div>\r\n");
              out.write("                                </div>\r\n");
              out.write("                                <div class=\"coltitle\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</div>\r\n");
              out.write("                                <div class=\"coltext\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</div>\r\n");
              out.write("                            </div>\r\n");
              out.write("                        </div>\r\n");
              out.write("                        <div class=\"coreply\">\r\n");
              out.write("                            <div class=\"core1\">\r\n");
              out.write("                                답변 :\r\n");
              out.write("                                0\r\n");
              out.write("                            </div>\r\n");
              out.write("                            <div class=\"renickname\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</div>\r\n");
              out.write("                            <div class=\"retime\">59분 전</div>\r\n");
              out.write("                        </div>\r\n");
              out.write("                        <hr class=\"listgard\">\r\n");
              out.write("                    </div>\r\n");
              out.write("					");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write("\r\n");
      out.write("                    <div class=\"content\">\r\n");
      out.write("                        <div class=\"colist\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <div class=\"colbt\">\r\n");
      out.write("                                    <img src=\"./resources/img/board/dogface.png\" alt=\"\">\r\n");
      out.write("                                    <div class=\"cattext1\">강아지</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"listbox\">\r\n");
      out.write("                                    <div class=\"cotextbox\">\r\n");
      out.write("                                        <div class=\"coltitle\">반려동물 침대에서 함께자나요?</div>\r\n");
      out.write("                                        <div class=\"coltext\">안녕하세요. 3년차 강아지 키우고 있는 아빠입니다. 처음 데려올 땐 \"사람과 동물이 어디 한 침대야~\" 라며 절대불가를 외쳤지만 지금은 잘때 한 방에 없으면 서운하고 꼭  불러서 침대로 오게 만드는 라이프를 살고 있습니다. 워낙 첨엔 숙면을 잘 못취하기도 하고, 불편했는데 그냥 매번 올라오는 강아지를 떨쳐낼 수가 없어 고민을 해결하다 못해 이런 가구는 어떨까 하며 여기까지 생각이 오게 되었습니다 ^^ 그냥 거창한 설문 조사는 아니고, 주변 반려인들께서는 어떤 잠자리를 하고 계실까 다른 반려동물들은 어떻게 침대에서 생활할까 궁금하기도 하고 자료가 필요하기도 하여 서투른 질문지들을 작성하여 이렇게 요청을 드립니다. 가벼운 마음으로, 작성해주시면 정말 감사하겠습니다. 추첨 통해 스타벅스 기프티콘 드려요! </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"imgbox\">\r\n");
      out.write("                                        <img class=\"listimg\" src=\"./resources/img/ggimu.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"coreply\">\r\n");
      out.write("                            <div class=\"core1\">\r\n");
      out.write("                                답변 :\r\n");
      out.write("                                0\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"renickname\">봉봉</div>\r\n");
      out.write("                            <div class=\"retime\">2시간 전</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"pagebutton\">\r\n");
      out.write("            <li class=\"leftbt\">\r\n");
      out.write("                <a href=\"#\" aria-label=\"Go to befor page\">‹</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"active\">\r\n");
      out.write("                <a class=\"undefined\" href=\"#\" aria-label=\"Go to page number 1\">1</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class>\r\n");
      out.write("                <a href=\"#\" aria-label=\"Go to page number 2\">2</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class>\r\n");
      out.write("                <a href=\"#\" aria-label=\"Go to page number 3\">3</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class>\r\n");
      out.write("                <a href=\"#\" aria-label=\"Go to page number 4\">4</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class>\r\n");
      out.write("                <a href=\"#\" aria-label=\"Go to page number 5\">5</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class>\r\n");
      out.write("                <a href=\"#\" aria-label=\"Go to after number \">›</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
