/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2023-02-21 13:54:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class commuwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");

	String name = (String)	session.getAttribute("username");
	System.out.println("session의 유저닉네임: "+name);

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>커뮤니티 게시글 등록</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./resources/css/qnawrite.css\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/014e61e9c4.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("	    function printfile(){\r\n");
      out.write("	        const name = document.getElementById('file1').value;\r\n");
      out.write("	        document.getElementById('result').value = name;\r\n");
      out.write("	    }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./header.jsp", out, false);
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"bbubbu\">\r\n");
      out.write("            <nav class=\"cos_nav\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li class = \"com_name\">\r\n");
      out.write("                        SHOP\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"lounge\">\r\n");
      out.write("        <div class=\"midlounge\">\r\n");
      out.write("            <div class=\"writebox\">\r\n");
      out.write("                <div id=\"bodertitlebox\">\r\n");
      out.write("                    <div class=\"title\" >\r\n");
      out.write("                        <h2 class=\"tltelcss\">게시글 작성</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <hr class=\"hrline\">\r\n");
      out.write("                    <div id=\"write_area\">\r\n");
      out.write("                        <form enctype=\"multipart/form-data\" action=\"./writeaction.action\" method=\"post\">\r\n");
      out.write("                        	<input type=\"hidden\" name=\"name\" value=\"");
      out.print(name);
      out.write("\">\r\n");
      out.write("                            <div id=\"in_title\">\r\n");
      out.write("                                <p class=\"titletxt\">제목</p>\r\n");
      out.write("                                <textarea name=\"title\" id=\"utitle\" rows=\"1\" cols=\"55\" maxlength=\"100\" required></textarea>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <hr class=\"hrline\">\r\n");
      out.write("                            <div id=\"in_content\">\r\n");
      out.write("                                <p class = \"contenttxt\">내용</p>\r\n");
      out.write("                                <textarea name=\"content\" id=\"ucontent\" required></textarea>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <hr class=\"hrline\">\r\n");
      out.write("                            <div class=\"filebox\">\r\n");
      out.write("                                <p class=\"filetitle\">첨부파일1</p>\r\n");
      out.write("                                <input class=\"upload-name\" id=\"result\" placeholder=\"첨부파일\"/>\r\n");
      out.write("                                <label for=\"file1\"> 파일찾기</label>\r\n");
      out.write("                                <input type=\"file\" name=\"file\" id=\"file1\" onchange=\"printfile()\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <hr class=\"hrline\">\r\n");
      out.write("                            <hr class=\"hrline\">\r\n");
      out.write("                            <div class=\"bt_se\">\r\n");
      out.write("                                <button class=\"subutton\" type=\"submit\">글 작성</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
