/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2023-02-21 13:54:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");

	String username = (String) session.getAttribute("username");
	String lv = (String) session.getAttribute("level");

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<style>\r\n");
      out.write("/* 초기화 */\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #fffef1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hea_con {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100px;\r\n");
      out.write("	background: #fec6ca;\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	z-index: 10;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* nav 시작 */\r\n");
      out.write("nav {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	width: 60%;\r\n");
      out.write("	height: 100px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_logo {\r\n");
      out.write("	margin-left: 20px;\r\n");
      out.write("	width: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_logo img {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_ul {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-around;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	width: 50%;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_login {\r\n");
      out.write("	margin-right: 20px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	background-color: #ff8fa4;\r\n");
      out.write("	padding: 5px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".member {\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".m_ddb {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	display: none;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	background-color: #fec6ca;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	padding: 5px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".m_ddb li {\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".admin {\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".a_ddb {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	display: none;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	background-color: #fec6ca;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	padding: 5px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".a_ddb li {\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_commu:hover .commu_div, .nav_notice:hover ul, .nav_hospital:hover ul,\r\n");
      out.write("	.nav_shop:hover ul {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_login:hover .loginbox {\r\n");
      out.write("	color: #bc9044;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".member:hover .m_ddb {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".admin:hover .a_ddb {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<title>header</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- 상단 -->\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"hea_con\">\r\n");
      out.write("			<nav>\r\n");
      out.write("				<div class=\"nav_logo\">\r\n");
      out.write("					<a href=\"./index.jsp\"><img src=\"./resources/img/logo3.png\"\r\n");
      out.write("						alt=\"Logo\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<ul class=\"nav_ul\">\r\n");
      out.write("					<li class=\"nav_commu\"><a href=\"./commuboard.action?pageNum=1\">커뮤니티</a></li>\r\n");
      out.write("					<li class=\"nav_notice\"><a href=\"#\">캣독마당</a></li>\r\n");
      out.write("					<li class=\"nav_hospital\"><a href=\"#\">우리동네</a></li>\r\n");
      out.write("					<li class=\"nav_shop\"><a href=\"#\">SHOP</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<div class=\"nav_login\">\r\n");
      out.write("					");

					if (username == null) {
					
      out.write("\r\n");
      out.write("					<div class=\"loginbox\">\r\n");
      out.write("						<a href=\"./login.do\">로그인</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					");

					} else if (username != null) {
					if (lv.equals("1")) {
					
      out.write("\r\n");
      out.write("					<div class=\"loginbox\">\r\n");
      out.write("						<div class=\"member\">\r\n");
      out.write("							<a href=\"#\">");
      out.print(username);
      out.write("님</a>\r\n");
      out.write("							<ul class=\"m_ddb\">\r\n");
      out.write("								<li><a href=\"#\">MyPage</a></li>\r\n");
      out.write("								<li><a href=\"#\">주문목록</a></li>\r\n");
      out.write("								<li><a href=\"#\">장바구니</a></li>\r\n");
      out.write("								<li><a href=\"#\">1:1 채팅창</a></li>\r\n");
      out.write("								<li><a href=\"./commuwrite.action\">글쓰기</a></li>\r\n");
      out.write("								<li><a href=\"./logout.jsp\">로그아웃</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					");

					} else if (lv.equals("2")) {
					
      out.write("\r\n");
      out.write("					<div class=\"loginbox\">\r\n");
      out.write("						<div class=\"admin\">\r\n");
      out.write("							<a href=\"#\">");
      out.print(username);
      out.write("님</a>\r\n");
      out.write("							<ul class=\"a_ddb\">\r\n");
      out.write("								<li><a href=\"#\">커뮤니티 관리</a></li>\r\n");
      out.write("								<li><a href=\"#\">캣독마당 관리</a></li>\r\n");
      out.write("								<li><a href=\"#\">우리동네병원 관리</a></li>\r\n");
      out.write("								<li><a href=\"#\">회원 관리</a></li>\r\n");
      out.write("								<li><a href=\"#\">SHOP 관리</a></li>\r\n");
      out.write("								<li><a href=\"./commuwrite.action\">글쓰기</a></li>\r\n");
      out.write("								<li><a href=\"./logout.jsp\">로그아웃</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					");

						}
					}
					
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
